#!/usr/bin/env bash
set -e

echo "Installing cr-bash..."

# Check if running as root
if [[ "$EUID" -ne 0 ]]; then
    SUDO="sudo"
else
    SUDO=""
fi

$SUDO mkdir -p /usr/local/bin/
$SUDO install -m 755 cr-bash /usr/local/bin/cr-bash

$SUDO mkdir -p /usr/local/share/man/man1
$SUDO install -m 644 cr-bash.1 /usr/local/share/man/man1/cr-bash.1

$SUDO mandb

echo "Installation complete. You can now run 'cr-bash'."